//@ -1,117 +0,0 @@
const pokemon = [
  {
    Name: "Miraidon (Iron Serpent)",
    OG: "Based on Cyclizar",
    Number: "1008",
    Type: ["Electric", "Dragon"],
    Image: `https://archives.bulbagarden.net/media/upload/9/94/Menu_SV_Miraidon.png`,
    Version: "Violet",
  },
  {
    Name: "Koraidon (Winged King)",
    OG: "Based on Cyclizar",
    Number: "1007",
    Type: ["Fighting", "Dragon"],
    Image: `https://archives.bulbagarden.net/media/upload/4/49/Menu_SV_Koraidon.png`,
    Version: "Scarlet",
  },
  {
    Name: "Iron Valiant",
    OG: "Based on Mega Gardevoir and Mega Gallade",
    Number: "1006",
    Type: ["Fairy", "Fighting"],
    Image: `https://archives.bulbagarden.net/media/upload/b/bf/Menu_SV_Iron_Valiant.png`,
    Version: "Violet",
  },
  {
    Name: "Roaring Moon",
    OG: "Based on Mega Salamence",
    Number: "1005",
    Type: ["Dragon", "Dark"],
    Image: `https://archives.bulbagarden.net/media/upload/1/1c/Menu_SV_Roaring_Moon.png`,
    Version: "Scarlet",
  },
  {
    Name: "Iron Thorns",
    OG: "Based on Tyranitar",
    Number: "995",
    Type: ["Rock", "Electric"],
    Image: `https://archives.bulbagarden.net/media/upload/1/1a/Menu_SV_Iron_Thorns.png`,
    Version: "Violet",
  },
  {
    Name: "Iron Moth",
    OG: "Based on Volcorona",
    Number: "994",
    Type: ["Fire", "Poison"],
    Image: `https://archives.bulbagarden.net/media/upload/3/33/Menu_SV_Iron_Moth.png`,
    Version: "Violet",
  },

  {
    Name: "Iron Jugulis",
    OG: "Based on Hydreigon",
    Number: "993",
    Type: ["Dark", "Flying"],
    Image: `https://archives.bulbagarden.net/media/upload/b/bc/Menu_SV_Iron_Jugulis.png`,
    Version: "Violet",
  },
  {
    Name: "Iron Hands",
    OG: "Based on Hariyama",
    Number: "992",
    Type: ["Fighting", "Electric"],
    Image: `https://archives.bulbagarden.net/media/upload/e/ed/Menu_SV_Iron_Hands.png`,
    Version: "Violet",
  },
  {
    Name: "Iron Bundle",
    OG: "Based on Delibird",
    Number: "991",
    Type: ["Ice", "Water"],
    Image: `https://archives.bulbagarden.net/media/upload/4/49/Menu_SV_Iron_Bundle.png`,
    Version: "Violet",
  },
  {
    Name: "Iron Treads",
    OG: "Based on Donphan",
    Number: "990",
    Type: ["Ground", "Steel"],
    Image: `https://archives.bulbagarden.net/media/upload/1/13/Menu_SV_Iron_Treads.png`,
    Version: "Violet",
  },
  {
    Name: "Flutter Mane",
    OG: "Based on Misdreavus",
    Number: "987",
    Type: ["Electric", "Ground"],
    Image: "https://archives.bulbagarden.net/media/upload/f/f4/Menu_SV_Flutter_Mane.png",
    Version: "Scarlet",
  },
  {
    Name: "Slither Wing",
    OG: "Based on Volcorona",
    Number: "988",
    Type: ["Bug", "Fighting"],
    Image: `https://archives.bulbagarden.net/media/upload/5/5e/Menu_SV_Slither_Wing.png`,
    Version: "Scarlet",
  },
  {
    Name: "Flutter Mane",
    OG: "Based on Misdreavus",
    Number: "987",
    Type: ["Electric", "Ground"],
    Image: "https://archives.bulbagarden.net/media/upload/f/f4/Menu_SV_Flutter_Mane.png",
    Version: "Scarlet",
  },
  {
    Name: "Brute Bonnet",
    OG: "Based on Amoonguss",
    Number: "986",
    Type: ["Grass", "Dark"],
    Image: `https://archives.bulbagarden.net/media/upload/c/c3/Menu_SV_Brute_Bonnet.png`,
    Version: "Scarlet",
  },
  {
    Name: "Scream Tail",
    OG: "Based on Jigglypuff",
    Number: "985",
    Type: ["Fairy", "Psychic"],
    Image: `https://archives.bulbagarden.net/media/upload/b/b7/Menu_SV_Scream_Tail.png`,
    Version: "Scarlet",
  },
  {
    Name: "Great Tusk",
    OG: "Based on Donphan",
    Number: "984",
    Type: ["Ground", "Fighting"],
    Image: `https://archives.bulbagarden.net/media/upload/c/ce/Menu_SV_Great_Tusk.png`,
    Version: "Scarlet",
  },
];

export { pokemon };

// const pokemon = [
//   {
//     Name: "Koraidon (Winged King)",
//     OG: "Cyclizar",
//     Number: "1007",
//     Type: ["Fighting", "Dragon"],
//     Image: `https://archives.bulbagarden.net/media/upload/4/49/Menu_SV_Koraidon.png`,
//     Version: "Scarlet",
//   },
//   {
//     Name: "Roaring Moon",
//     OG: "Mega Salamence",
//     Number: "1005",
//     Type: ["Dragon", "Dark"],
//     Image: `https://archives.bulbagarden.net/media/upload/1/1c/Menu_SV_Roaring_Moon.png`,
//     Version: "Scarlet",
//   },
//   {
//     Name: "Great Tusk",
//     OG: "Donphan",
//     Number: "984",
//     Type: ["Ground", "Fighting"],
//     Image: `https://archives.bulbagarden.net/media/upload/c/ce/Menu_SV_Great_Tusk.png`,
//     Version: "Scarlet",
//   },
//   {
//     Name: "Slither Wing",
//     OG: "Volcorona",
//     Number: "988",
//     Type: ["Bug", "Fighting"],
//     Image: `https://archives.bulbagarden.net/media/upload/5/5e/Menu_SV_Slither_Wing.png`,
//     Version: "Scarlet",
//   },
//   {
//     Name: "Scream Tail",
//     OG: "Jigglypuff",
//     Number: "985",
//     Type: ["Fairy", "Psychic"],
//     Image: `https://archives.bulbagarden.net/media/upload/b/b7/Menu_SV_Scream_Tail.png`,
//     Version: "Scarlet",
//   },
//   {
//     Name: "Brute Bonnet",
//     OG: "Amoonguss",
//     Number: "986",
//     Type: ["Grass", "Dark"],
//     Image: `https://archives.bulbagarden.net/media/upload/c/c3/Menu_SV_Brute_Bonnet.png`,
//     Version: "Scarlet",
//   },
//   {
//     Name: "Flutter Mane",
//     OG: "Misdreavus",
//     Number: "987",
//     Type: ["Electric", "Ground"],
//     Image: "https://archives.bulbagarden.net/media/upload/f/f4/Menu_SV_Flutter_Mane.png",
//     Version: "Scarlet",
//   },
//   {
//     Name: "Sandy Shocks",
//     OG: "Magneton",
//     Number: "989",
//     Type: ["Electric", "Ground"],
//     Image: `https://archives.bulbagarden.net/media/upload/8/8c/Menu_SV_Sandy_Shocks.png`,
//     Version: "Scarlet",
//   },
//   {
//     Name: "Miraidon (Iron Serpent)",
//     OG: "Cyclizar",
//     Number: "1008",
//     Type: ["Electric", "Dragon"],
//     Image: `https://archives.bulbagarden.net/media/upload/9/94/Menu_SV_Miraidon.png`,
//     Version: "Violet",
//   },
//   {
//     Name: "Iron Valiant",
//     OG: "Mega Gardevoir, Mega Gallade",
//     Number: "1006",
//     Type: ["Fairy", "Fighting"],
//     Image: `https://archives.bulbagarden.net/media/upload/b/bf/Menu_SV_Iron_Valiant.png`,
//     Version: "Violet",
//   },
//   {
//     Name: "Iron Treads",
//     OG: "Donphan",
//     Number: "990",
//     Type: ["Ground", "Steel"],
//     Image: `https://archives.bulbagarden.net/media/upload/1/13/Menu_SV_Iron_Treads.png`,
//     Version: "Violet",
//   },
//   {
//     Name: "Iron Moth",
//     OG: "Volcorona",
//     Number: "994",
//     Type: ["Fire", "Poison"],
//     Image: `https://archives.bulbagarden.net/media/upload/3/33/Menu_SV_Iron_Moth.png`,
//     Version: "Violet",
//   },
//   {
//     Name: "Iron Bundle",
//     OG: "Delibird",
//     Number: "991",
//     Type: ["Ice", "Water"],
//     Image: `https://archives.bulbagarden.net/media/upload/4/49/Menu_SV_Iron_Bundle.png`,
//     Version: "Violet",
//   },
//   {
//     Name: "Iron Hands",
//     OG: "Hariyama",
//     Number: "992",
//     Type: ["Fighting", "Electric"],
//     Image: `https://archives.bulbagarden.net/media/upload/e/ed/Menu_SV_Iron_Hands.png`,
//     Version: "Violet",
//   },
//   {
//     Name: "Iron Jugulis",
//     OG: "Hydreigon",
//     Number: "993",
//     Type: ["Dark", "Flying"],
//     Image: `https://archives.bulbagarden.net/media/upload/b/bc/Menu_SV_Iron_Jugulis.png`,
//     Version: "Violet",
//   },
//   {
//     Name: "Iron Thorns",
//     OG: "Tyranitar",
//     Number: "995",
//     Type: ["Rock", "Electric"],
//     Image: `https://archives.bulbagarden.net/media/upload/1/1a/Menu_SV_Iron_Thorns.png`,
//     Version: "Violet",
//   },
// ];

// export { pokemon };
