export const Spokemon = [
    {
        Name: "Koraidon",
        OG: "Cyclizar",
        Number: "1007",
        Type: ['Fighting', 'Dragon'],
        Image: ,
    },
    {
        Name: "Roaring Moon",
        OG: "Mega Salamence",
        Number: "1005",
        Type: ['Dragon', 'Dark'],
        Image: ,
    },
    {
        Name: "Great Tusk",
        OG: "Donphan",
        Number: "984",
        Type: ['Ground', 'Fighting'],
        Image: ,
    },
    {
        Name: "Slither Wing",
        OG: "Volcorona",
        Number: "988",
        Type: ['Bug', 'Fighting'],
        Image: ,
    },
    {
        Name: "Scream Tail",
        OG: "Jigglypuff",
        Number: "985",
        Type: ['Fairy', 'Psychic'],
        Image: ,
    },
    {
        Name: "Brute Bonnet",
        OG: "Amoonguss",
        Number: "986",
        Type: ['Grass', 'Dark'],
        Image: ,
    },
    {
        Name: "Flutter Mane",
        OG: "Misdreavus",
        Number: "987",
        Type: ['Electric', 'Ground'],
        Image: ,
    },
    {
        Name: "Sandy Shocks",
        OG: "Magneton",
        Number: "989",
        Type: ['Electric', 'Ground'],
        Image: ,
    },
]
export const Vpokemon = [
    {
        Name: "Miraidon",
        OG: "Cyclizar",
        Number: "1008",
        Type: ['Electric', 'Dragon'],
        Image: ,
    },
    {
        Name: "Iron Valiant",
        OG: "Mega Gardevoir, Mega Gallade",
        Number: "1006",
        Type: ['Fairy', 'Fighting'],
        Image: ,
    },
    {
        Name: "Iron Treads",
        OG: "Donphan",
        Number: "990",
        Type: ['Ground', 'Steel'],
        Image: ,
    },
    {
        Name: "Iron Moth",
        OG: "Volcorona",
        Number: "994",
        Type: ['Fire', 'Poison'],
        Image: ,
    },
    {
        Name: "Iron Bundle",
        OG: "Delibird",
        Number: "991",
        Type: ['Ice', 'Water'],
        Image: ,
    },
    {
        Name: "Iron Hands",
        OG: "Hariyama",
        Number: "992",
        Type: ['Fighting', 'Electric'],
        Image: ,
    },
    {
        Name: "Iron Jugulis",
        OG: "Hydreigon",
        Number: "993",
        Type: ['Dark', 'Flying'],
        Image: ,
    },
    {
        Name: "Iron Thorns",
        OG: "Tyranitar",
        Number: "995",
        Type: ['Rock', 'Electric'],
        Image: ,
    },
]