export const Spokemon = [
  {
    Name: "Koraidon",
    OG: "Cyclizar",
    Number: "1007",
    Type: ["Fighting", "Dragon"],
    Image: `https://archives.bulbagarden.net/media/upload/thumb/2/24/Koraidon.png/600px-Koraidon.png`,
  },
  {
    Name: "Roaring Moon",
    OG: "Mega Salamence",
    Number: "1005",
    Type: ["Dragon", "Dark"],
    Image: `https://archives.bulbagarden.net/media/upload/1/1c/Menu_SV_Roaring_Moon.png`,
  },
  {
    Name: "Great Tusk",
    OG: "Donphan",
    Number: "984",
    Type: ["Ground", "Fighting"],
    Image: `https://archives.bulbagarden.net/media/upload/0/09/Great_Tusk.png`,
  },
  {
    Name: "Slither Wing",
    OG: "Volcorona",
    Number: "988",
    Type: ["Bug", "Fighting"],
    Image: `https://archives.bulbagarden.net/media/upload/5/5e/Menu_SV_Slither_Wing.png`,
  },
  {
    Name: "Scream Tail",
    OG: "Jigglypuff",
    Number: "985",
    Type: ["Fairy", "Psychic"],
    Image: `https://archives.bulbagarden.net/media/upload/b/b7/Menu_SV_Scream_Tail.png`,
  },
  {
    Name: "Brute Bonnet",
    OG: "Amoonguss",
    Number: "986",
    Type: ["Grass", "Dark"],
    Image: `https://archives.bulbagarden.net/media/upload/c/c3/Menu_SV_Brute_Bonnet.png`,
  },
  {
    Name: "Flutter Mane",
    OG: "Misdreavus",
    Number: "987",
    Type: ["Electric", "Ground"],
    Image:
      "https://archives.bulbagarden.net/media/upload/f/f4/Menu_SV_Flutter_Mane.png",
  },
  {
    Name: "Sandy Shocks",
    OG: "Magneton",
    Number: "989",
    Type: ["Electric", "Ground"],
    Image: `https://archives.bulbagarden.net/media/upload/8/8c/Menu_SV_Sandy_Shocks.png`,
  },
];
export const Vpokemon = [
  {
    Name: "Miraidon",
    OG: "Cyclizar",
    Number: "1008",
    Type: ["Electric", "Dragon"],
    Image: `https://archives.bulbagarden.net/media/upload/f/fb/Miraidon.png`,
  },
  {
    Name: "Iron Valiant",
    OG: "Mega Gardevoir, Mega Gallade",
    Number: "1006",
    Type: ["Fairy", "Fighting"],
    Image: `https://archives.bulbagarden.net/media/upload/b/bf/Menu_SV_Iron_Valiant.png`,
  },
  {
    Name: "Iron Treads",
    OG: "Donphan",
    Number: "990",
    Type: ["Ground", "Steel"],
    Image: `https://archives.bulbagarden.net/media/upload/7/76/Iron_Treads.png`,
  },
  {
    Name: "Iron Moth",
    OG: "Volcorona",
    Number: "994",
    Type: ["Fire", "Poison"],
    Image: `https://archives.bulbagarden.net/media/upload/3/33/Menu_SV_Iron_Moth.png`,
  },
  {
    Name: "Iron Bundle",
    OG: "Delibird",
    Number: "991",
    Type: ["Ice", "Water"],
    Image: `https://archives.bulbagarden.net/media/upload/4/49/Menu_SV_Iron_Bundle.png`,
  },
  {
    Name: "Iron Hands",
    OG: "Hariyama",
    Number: "992",
    Type: ["Fighting", "Electric"],
    Image: `https://archives.bulbagarden.net/media/upload/e/ed/Menu_SV_Iron_Hands.png`,
  },
  {
    Name: "Iron Jugulis",
    OG: "Hydreigon",
    Number: "993",
    Type: ["Dark", "Flying"],
    Image: `https://archives.bulbagarden.net/media/upload/b/bc/Menu_SV_Iron_Jugulis.png`,
  },
  {
    Name: "Iron Thorns",
    OG: "Tyranitar",
    Number: "995",
    Type: ["Rock", "Electric"],
    Image: `https://archives.bulbagarden.net/media/upload/1/1a/Menu_SV_Iron_Thorns.png`,
  },
];
